var puestoDesempenado = {
    "datos": [
        { "codigo": "2421", "descripcion": "Abogados" },
        { "codigo": "5142", "descripcion": "Acompañantes y ayudas de cámara" },
        { "codigo": "2455", "descripcion": "Actores y directores de cine, radio, teatro, televisión y afines" },
        { "codigo": "5152", "descripcion": "Adivinadores, quirománticos y afines" },
        { "codigo": "3429", "descripcion": "Agentes comerciales y corredores, no clasificados bajo otros epígrafes" },
        { "codigo": "3441", "descripcion": "Agentes de aduana e inspectores de fronteras" },
        { "codigo": "3411", "descripcion": "Agentes de bolsa, cambio y otros servicios financieros" },
        { "codigo": "3421", "descripcion": "Agentes de compras y consignatarios" },
        { "codigo": "3449", "descripcion": "Agentes de las administraciones públicas de aduanas, impuestos y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "3412", "descripcion": "Agentes de seguros" },
        { "codigo": "3414", "descripcion": "Agentes de viajes" },
        { "codigo": "3413", "descripcion": "Agentes inmobiliarios" },
        { "codigo": "3423", "descripcion": "Agentes públicos y privados de colocación y contratistas de mano de obra" },
        { "codigo": "6111", "descripcion": "Agricultores y trabajadores calificados de cultivos extensivos" },
        { "codigo": "6114", "descripcion": "Agricultores y trabajadores calificados de cultivos mixtos" },
        { "codigo": "6113", "descripcion": "Agricultores y trabajadores calificados de huertas, invernaderos, viveros y jardines" },
        { "codigo": "6112", "descripcion": "Agricultores y trabajadores calificados de plantaciones de árboles y arbustos" },
        { "codigo": "2213", "descripcion": "Agrónomos y afines" },
        { "codigo": "7242", "descripcion": "Ajustadores electronicistas" },
        { "codigo": "7122", "descripcion": "Albañiles y mamposteros" },
        { "codigo": "7321", "descripcion": "Alfareros y afines (barro, arcilla y abrasivos)" },
        { "codigo": "7215", "descripcion": "Aparejadores y empalmadores de cables" },
        { "codigo": "7441", "descripcion": "Apelambradores, pellejeros y curtidores" },
        { "codigo": "6123", "descripcion": "Apicultores y sericicultores y trabajadores calificados de la apicultura y la sericicultura" },
        { "codigo": "2431", "descripcion": "Archiveros y conservadores de museos" },
        { "codigo": "2149", "descripcion": "Arquitectos, ingenieros y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "2141", "descripcion": "Arquitectos, urbanistas e ingenieros de tránsito" },
        { "codigo": "7331", "descripcion": "Artesanos de la madera y materiales similares" },
        { "codigo": "7332", "descripcion": "Artesanos de los tejidos, el cuero y materiales similares" },
        { "codigo": "5151", "descripcion": "Astrólogos y afines" },
        { "codigo": "3475", "descripcion": "Atletas, deportistas y afines" },
        { "codigo": "2451", "descripcion": "Autores, periodistas y otros escritores" },
        { "codigo": "3480", "descripcion": "Auxiliares laicos de los cultos" },
        { "codigo": "6122", "descripcion": "Avicultores y trabajadores calificados de la avicultura" },
        { "codigo": "5133", "descripcion": "Ayudantes de enfermería a domicilio" },
        { "codigo": "5132", "descripcion": "Ayudantes de enfermería en instituciones" },
        { "codigo": "7142", "descripcion": "Barnizadores y afines" },
        { "codigo": "9162", "descripcion": "Barrenderos y afines" },
        { "codigo": "2432", "descripcion": "Bibliotecarios, documentalistas y afines" },
        { "codigo": "2211", "descripcion": "Biólogos, botánicos, zoólogos y afines" },
        { "codigo": "5161", "descripcion": "Bomberos" },
        { "codigo": "7216", "descripcion": "Buzos" },
        { "codigo": "4211", "descripcion": "Cajeros y expendedores de billetes" },
        { "codigo": "7341", "descripcion": "Cajistas, tipógrafos y afines" },
        { "codigo": "5111", "descripcion": "Camareros y azafatas" },
        { "codigo": "5123", "descripcion": "Camareros y taberneros" },
        { "codigo": "3142", "descripcion": "Capitanes, oficiales de cubierta y prácticos" },
        { "codigo": "6142", "descripcion": "Carboneros de carbón vegetal y afines" },
        { "codigo": "7411", "descripcion": "Carniceros, pescaderos y afines" },
        { "codigo": "7124", "descripcion": "Carpinteros de armar y de blanco" },
        { "codigo": "2148", "descripcion": "Cartógrafos y agrimensores" },
        { "codigo": "7415", "descripcion": "Catadores y clasificadores de alimentos y bebidas" },
        { "codigo": "6154", "descripcion": "Cazadores y tramperos" },
        { "codigo": "7424", "descripcion": "Cesteros, bruceros y afines" },
        { "codigo": "7213", "descripcion": "Chapistas y caldereros" },
        { "codigo": "4215", "descripcion": "Cobradores y afines" },
        { "codigo": "5122", "descripcion": "Cocineros" },
        { "codigo": "4143", "descripcion": "Codificadores de datos, correctores de pruebas de imprenta y afines" },
        { "codigo": "2453", "descripcion": "Compositores, músicos y cantantes" },
        { "codigo": "3416", "descripcion": "Compradores" },
        { "codigo": "8323", "descripcion": "Conductores de autobuses y tranvías" },
        { "codigo": "8322", "descripcion": "Conductores de automóviles, taxis y camionetas" },
        { "codigo": "8324", "descripcion": "Conductores de camiones pesados" },
        { "codigo": "8321", "descripcion": "Conductores de motocicletas" },
        { "codigo": "9331", "descripcion": "Conductores de vehículos accionados a pedal o a brazo" },
        { "codigo": "9332", "descripcion": "Conductores de vehículos y máquinas de tracción animal" },
        { "codigo": "3213", "descripcion": "Consejeros agrícolas y forestales" },
        { "codigo": "9141", "descripcion": "Conserjes" },
        { "codigo": "7121", "descripcion": "Constructores con técnicas y materiales tradicionales" },
        { "codigo": "7312", "descripcion": "Constructores y afinadores de instrumentos musicales" },
        { "codigo": "2411", "descripcion": "Contadores" },
        { "codigo": "3144", "descripcion": "Controladores de tráfico aéreo" },
        { "codigo": "2454", "descripcion": "Coreógrafos y bailarines" },
        { "codigo": "7436", "descripcion": "Costureros, bordadores y afines" },
        { "codigo": "2131", "descripcion": "Creadores y analistas de sistemas informáticos" },
        { "codigo": "6151", "descripcion": "Criadores de especies acuáticas" },
        { "codigo": "6121", "descripcion": "Criadores de ganado y otros animales domésticos, productores de leche y sus derivados" },
        { "codigo": "6124", "descripcion": "Criadores y trabajadores calificados de la cría de animales domésticos diversos" },
        { "codigo": "6129", "descripcion": "Criadores y trabajadores pecuarios calificados de cría de animales p mercado y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "7135", "descripcion": "Cristaleros" },
        { "codigo": "3242", "descripcion": "Curanderos" },
        { "codigo": "3422", "descripcion": "Declarantes o gestores de aduana" },
        { "codigo": "3471", "descripcion": "Decoradores y diseñadores" },
        { "codigo": "3118", "descripcion": "Delineantes y dibujantes técnicos" },
        { "codigo": "3225", "descripcion": "Dentistas auxiliares y ayudantes de odontología" },
        { "codigo": "1235", "descripcion": "Directores de departamentos de abastecimiento y distribución" },
        { "codigo": "1237", "descripcion": "Directores de departamentos de investigaciones y desarrollo" },
        { "codigo": "1232", "descripcion": "Directores de departamentos de personal y de relaciones laborales" },
        { "codigo": "1221", "descripcion": "Directores de departamentos de producción y operaciones, agricultura, caza, silvicultura y pesca" },
        { "codigo": "1224", "descripcion": "Directores de departamentos de producción y operaciones, comercio mayorista y minorista" },
        { "codigo": "1223", "descripcion": "Directores de departamentos de producción y operaciones, construcción y obras públicas" },
        { "codigo": "1227", "descripcion": "Directores de departamentos de producción y operaciones, empresas de intermediación y servicios a empresas" },
        { "codigo": "1222", "descripcion": "Directores de departamentos de producción y operaciones, industrias manufactureras" },
        { "codigo": "1229", "descripcion": "Directores de departamentos de producción y operaciones, no clasificados bajo otros epígrafes" },
        { "codigo": "1225", "descripcion": "Directores de departamentos de producción y operaciones, restauración y hostelería" },
        { "codigo": "1228", "descripcion": "Directores de departamentos de producción y operaciones, servicios de cuidados personales, limpieza y servicios similares" },
        { "codigo": "1226", "descripcion": "Directores de departamentos de producción y operaciones, transporte, almacenamiento y comunicaciones" },
        { "codigo": "1234", "descripcion": "Directores de departamentos de publicidad y de relaciones públicas" },
        { "codigo": "1236", "descripcion": "Directores de departamentos de servicios de informática" },
        { "codigo": "1233", "descripcion": "Directores de departamentos de ventas y comercialización" },
        { "codigo": "1231", "descripcion": "Directores de departamentos financieros y administrativos" },
        { "codigo": "1210", "descripcion": "Directores generales y gerentes generales de empresa" },
        { "codigo": "1142", "descripcion": "Dirigentes y administradores de organizaciones de empleadores, de trabajadores y de otras de interés socioeconómico" },
        { "codigo": "1143", "descripcion": "Dirigentes y administradores de organizaciones humanitarias y de otras organizaciones especializadas" },
        { "codigo": "1141", "descripcion": "Dirigentes y administradores de partidos políticos" },
        { "codigo": "7422", "descripcion": "Ebanistas y afines" },
        { "codigo": "2441", "descripcion": "Economistas" },
        { "codigo": "5121", "descripcion": "Ecónomos, mayordomos y afines" },
        { "codigo": "7137", "descripcion": "Electricistas de obras y afines" },
        { "codigo": "3113", "descripcion": "Electrotécnicos" },
        { "codigo": "9322", "descripcion": "Embaladores manuales y otros peones de la industria manufacturera" },
        { "codigo": "4221", "descripcion": "Empleados de agencias de viajes" },
        { "codigo": "4141", "descripcion": "Empleados de bibliotecas y archivos" },
        { "codigo": "4121", "descripcion": "Empleados de contabilidad y cálculo de costos" },
        { "codigo": "4131", "descripcion": "Empleados de control de abastecimientos inventario" },
        { "codigo": "4132", "descripcion": "Empleados de servicios de apoyo a la producción" },
        { "codigo": "4142", "descripcion": "Empleados de servicios de correos" },
        { "codigo": "4133", "descripcion": "Empleados de servicios de transporte" },
        { "codigo": "4122", "descripcion": "Empleados de servicios estadísticos y financieros" },
        { "codigo": "7345", "descripcion": "Encuadernadores y afines" },
        { "codigo": "4144", "descripcion": "Escribientes públicos y afines" },
        { "codigo": "2452", "descripcion": "Escultores, pintores y afines" },
        { "codigo": "2351", "descripcion": "Especialistas en métodos pedagógicos y material didáctico" },
        { "codigo": "2419", "descripcion": "Especialistas en organización y administración de empresas y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "2412", "descripcion": "Especialistas en políticas y servicios de personal y afines" },
        { "codigo": "2122", "descripcion": "Estadísticos" },
        { "codigo": "7342", "descripcion": "Estereotipistas y galvanotipistas" },
        { "codigo": "2224", "descripcion": "Farmacéuticos" },
        { "codigo": "2212", "descripcion": "Farmacólogos, patólogos y afines" },
        { "codigo": "2444", "descripcion": "Filólogos, traductores e intérpretes" },
        { "codigo": "2443", "descripcion": "Filósofos, historiadores y especialistas en ciencias políticas" },
        { "codigo": "3226", "descripcion": "Fisioterapeutas y afines" },
        { "codigo": "7136", "descripcion": "Fontaneros e instaladores de tuberías" },
        { "codigo": "3131", "descripcion": "Fotógrafos y operadores de equipos de grabación de imagen y sonido" },
        { "codigo": "0110", "descripcion": "Fuerzas armadas" },
        { "codigo": "3444", "descripcion": "Funcionarios de servicios de expedición de licencias y permisos" },
        { "codigo": "3443", "descripcion": "Funcionarios de servicios de seguridad social" },
        { "codigo": "3442", "descripcion": "Funcionarios del fisco" },
        { "codigo": "2111", "descripcion": "Físicos y astrónomos" },
        { "codigo": "1314", "descripcion": "Gerentes de comercios mayoristas y minoristas" },
        { "codigo": "1311", "descripcion": "Gerentes de empresas de agricultura, caza, silvicultura y pesca" },
        { "codigo": "1313", "descripcion": "Gerentes de empresas de construcción y obras públicas" },
        { "codigo": "1317", "descripcion": "Gerentes de empresas de intermediación y servicios a empresas" },
        { "codigo": "1315", "descripcion": "Gerentes de empresas de restauración y hostelería" },
        { "codigo": "1318", "descripcion": "Gerentes de empresas de servicios de cuidados Personales, limpieza y servicios similares" },
        { "codigo": "1316", "descripcion": "Gerentes de empresas de transporte, almacenamiento y comunicaciones" },
        { "codigo": "1319", "descripcion": "Gerentes de empresas, no clasificados bajo otros epígrafes" },
        { "codigo": "1312", "descripcion": "Gerentes de industrias manufactureras" },
        { "codigo": "2114", "descripcion": "Geólogos y geofísicos" },
        { "codigo": "7343", "descripcion": "Grabadores de imprenta y fotograbadores" },
        { "codigo": "7323", "descripcion": "Grabadores de vidrio" },
        { "codigo": "8312", "descripcion": "Guardafrenos, guardagujas y agentes de maniobras" },
        { "codigo": "5163", "descripcion": "Guardianes de prisión" },
        { "codigo": "5113", "descripcion": "Guías" },
        { "codigo": "7222", "descripcion": "Herramentistas y afines" },
        { "codigo": "7221", "descripcion": "Herreros y forjadores" },
        { "codigo": "3222", "descripcion": "Higienistas y otro personal sanitario" },
        { "codigo": "7346", "descripcion": "Impresores de sericigrafía y estampadores a la plancha y en textiles" },
        { "codigo": "2142", "descripcion": "Ingenieros civiles" },
        { "codigo": "2147", "descripcion": "Ingenieros de minas y metalúrgicos y afines" },
        { "codigo": "2143", "descripcion": "Ingenieros electricistas" },
        { "codigo": "2144", "descripcion": "Ingenieros electronicistas y de telecomunicaciones" },
        { "codigo": "2145", "descripcion": "Ingenieros mecánicos" },
        { "codigo": "2146", "descripcion": "Ingenieros químicos" },
        { "codigo": "3151", "descripcion": "Inspectores de edificios y de prevención e investigación de incendios" },
        { "codigo": "2352", "descripcion": "Inspectores de la enseñanza" },
        { "codigo": "3450", "descripcion": "Inspectores de policía y detectives" },
        { "codigo": "3152", "descripcion": "Inspectores de seguridad y salud y control de calidad" },
        { "codigo": "7134", "descripcion": "Instaladores de material aislante y de insonorización" },
        { "codigo": "7245", "descripcion": "Instaladores y reparadores de líneas eléctricas" },
        { "codigo": "7244", "descripcion": "Instaladores y reparadores de telégrafos y teléfonos" },
        { "codigo": "1130", "descripcion": "Jefes de pequeñas poblaciones" },
        { "codigo": "7313", "descripcion": "Joyeros, orfebres y plateros" },
        { "codigo": "2422", "descripcion": "Jueces" },
        { "codigo": "9142", "descripcion": "Lavadores de vehículos, ventanas y afines" },
        { "codigo": "9133", "descripcion": "Lavanderos y planchadores manuales" },
        { "codigo": "9120", "descripcion": "Limpiabotas y otros trabajador-es callejeros" },
        { "codigo": "7143", "descripcion": "Limpiadores de fachadas y deshollinadores" },
        { "codigo": "9132", "descripcion": "Limpiadores de oficinas, hoteles y otros establecimientos" },
        { "codigo": "3472", "descripcion": "Locutores de radio y televisión y afines" },
        { "codigo": "3330", "descripcion": "Maestros de nivel medio de la enseñanza especial" },
        { "codigo": "3320", "descripcion": "Maestros de nivel medio de la enseñanza preescolar" },
        { "codigo": "3310", "descripcion": "Maestros de nivel medio de la enseñanza primaria" },
        { "codigo": "2332", "descripcion": "Maestros de nivel superior de la enseñanza preescolar" },
        { "codigo": "2331", "descripcion": "Maestros de nivel superior de la enseñanza primaria" },
        { "codigo": "2340", "descripcion": "Maestros e instructores de nivel superior de la enseñanza especial" },
        { "codigo": "8311", "descripcion": "Maquinistas de locomotoras" },
        { "codigo": "8340", "descripcion": "Marineros de cubierta y afines" },
        { "codigo": "2121", "descripcion": "Matemáticos y afines" },
        { "codigo": "7232", "descripcion": "Mecánicos y ajustadores de motores de avión" },
        { "codigo": "7233", "descripcion": "Mecánicos y ajustadores de máquinas agrícolas e industriales" },
        { "codigo": "7231", "descripcion": "Mecánicos y ajustadores de vehículos de motor" },
        { "codigo": "7241", "descripcion": "Mecánicos y ajustadores electricistas" },
        { "codigo": "7243", "descripcion": "Mecánicos y reparadores de aparatos electrónicos" },
        { "codigo": "7311", "descripcion": "Mecánicos y reparadores de instrumentos de precisión" },
        { "codigo": "9151", "descripcion": "Mensajeros, porteadores y repartidores" },
        { "codigo": "2112", "descripcion": "Meteorólogos" },
        { "codigo": "1110", "descripcion": "Miembros del poder ejecutivo y de los cuerpos legislativos" },
        { "codigo": "7111", "descripcion": "Mineros y canteros" },
        { "codigo": "5210", "descripcion": "Modelos de modas, arte y publicidad" },
        { "codigo": "7211", "descripcion": "Moldeadores y macheros" },
        { "codigo": "8283", "descripcion": "Montadores de equipos electrónicos" },
        { "codigo": "8282", "descripcion": "Montadores de equipos eléctricos" },
        { "codigo": "7214", "descripcion": "Montadores de estructuras metálicas" },
        { "codigo": "8281", "descripcion": "Montadores de mecanismos y elementos mecánicos de máquinas" },
        { "codigo": "8286", "descripcion": "Montadores de productos de cartón, textiles y materiales afines" },
        { "codigo": "8285", "descripcion": "Montadores de productos de madera y de materiales afines" },
        { "codigo": "8284", "descripcion": "Montadores de productos metálicos, de caucho y de material plástico" },
        { "codigo": "9211", "descripcion": "Mozos de labranza y peones agropecuarios" },
        { "codigo": "2221", "descripcion": "Médicos" },
        { "codigo": "2229", "descripcion": "Médicos y profesionales afines (excepto el personal de enfermería y partería), no clasificados bajo otros epígrafes" },
        { "codigo": "3473", "descripcion": "Músicos, cantantes y bailarines callejeros, de cabaret y afines" },
        { "codigo": "5131", "descripcion": "Niñeras y celadoras infantiles" },
        { "codigo": "2222", "descripcion": "Odontólogos" },
        { "codigo": "3141", "descripcion": "Oficiales maquinistas" },
        { "codigo": "7129", "descripcion": "Oficiales y operarios de la construcción (obra gruesa) y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "3133", "descripcion": "Operadores de aparatos de diagnóstico y tratamiento médicos" },
        { "codigo": "8171", "descripcion": "Operadores de cadenas de montaje automatizadas" },
        { "codigo": "4114", "descripcion": "Operadores de calculadoras" },
        { "codigo": "8334", "descripcion": "Operadores de carretillas elevadoras" },
        { "codigo": "4113", "descripcion": "Operadores de entrada de datos" },
        { "codigo": "8154", "descripcion": "Operadores de equipos de destilación y de reacción química (excepto petróleo y gas natural)" },
        { "codigo": "8153", "descripcion": "Operadores de equipos de filtración y separación de sustancias químicas" },
        { "codigo": "3132", "descripcion": "Operadores de equipos de radiodifusión, televisión y telecomunicaciones" },
        { "codigo": "3139", "descripcion": "Operadores de equipos ópticos y electrónicos, no clasificados bajo otros epígrafes" },
        { "codigo": "8333", "descripcion": "Operadores de grúas, de aparatos elevadores y afines" },
        { "codigo": "8122", "descripcion": "Operadores de homos de segunda fusión, máquinas de colar y moldear metales y trenes de laminación" },
        { "codigo": "8131", "descripcion": "Operadores de homos de vidriería y cerámica y operadores de máquinas afines" },
        { "codigo": "8121", "descripcion": "Operadores de hornos de minerales y de hornos de primera fusión de metales" },
        { "codigo": "8163", "descripcion": "Operadores de incineradores, instalaciones de tratamiento de agua y afines" },
        { "codigo": "8141", "descripcion": "Operadores de instalaciones de procesamiento de la madera" },
        { "codigo": "8112", "descripcion": "Operadores de instalaciones de procesamiento de minerales y rocas" },
        { "codigo": "8161", "descripcion": "Operadores de instalaciones de producción de energía" },
        { "codigo": "8155", "descripcion": "Operadores de instalaciones de refinación de petróleo y gas natural" },
        { "codigo": "8152", "descripcion": "Operadores de instalaciones de tratamiento químico térmico" },
        { "codigo": "8123", "descripcion": "Operadores de instalaciones de tratamiento térmico de metales" },
        { "codigo": "8159", "descripcion": "Operadores de instalaciones de tratamientos químicos. no clasificados bajo otros epígrafes" },
        { "codigo": "8139", "descripcion": "Operadores de instalaciones de vidriería, cerámica y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "8111", "descripcion": "Operadores de instalaciones mineras" },
        { "codigo": "8143", "descripcion": "Operadores de instalaciones para la fabricación de papel" },
        { "codigo": "8142", "descripcion": "Operadores de instalaciones para la preparación de pasta para papel" },
        { "codigo": "8151", "descripcion": "Operadores de instalaciones quebrantadoras, trituradoras y mezcladoras de sustancias químicas" },
        { "codigo": "8331", "descripcion": "Operadores de maquinaria agrícola y forestal motorizada" },
        { "codigo": "8264", "descripcion": "Operadores de máquinas de blanqueo, teñido y tintura" },
        { "codigo": "8252", "descripcion": "Operadores de máquinas de encuadernación" },
        { "codigo": "8251", "descripcion": "Operadores de máquinas de imprenta" },
        { "codigo": "8332", "descripcion": "Operadores de máquinas de movimiento de tierras y afines" },
        { "codigo": "8261", "descripcion": "Operadores de máquinas de preparación de fibras, hilado y devanado" },
        { "codigo": "8265", "descripcion": "Operadores de máquinas de tratamiento de pieles y cueros" },
        { "codigo": "4112", "descripcion": "Operadores de máquinas de tratamiento de textos y afines" },
        { "codigo": "8162", "descripcion": "Operadores de máquinas de vapor y calderas" },
        { "codigo": "8211", "descripcion": "Operadores de máquinas herramientas" },
        { "codigo": "8263", "descripcion": "Operadores de máquinas para coser" },
        { "codigo": "8271", "descripcion": "Operadores de máquinas para elaborar carne, pescado y mariscos" },
        { "codigo": "8274", "descripcion": "Operadores de máquinas para elaborar cereales, productos de panadería y repostería y artículos de chocolate" },
        { "codigo": "8278", "descripcion": "Operadores de máquinas para elaborar cerveza, vinos y otras bebidas" },
        { "codigo": "8275", "descripcion": "Operadores de máquinas para elaborar frutos húmedos y secos y hortalizas" },
        { "codigo": "8279", "descripcion": "Operadores de máquinas para elaborar productos del tabaco" },
        { "codigo": "8272", "descripcion": "Operadores de máquinas para elaborar productos lácteos" },
        { "codigo": "8277", "descripcion": "Operadores de máquinas para elaborar té, café y cacao" },
        { "codigo": "8224", "descripcion": "Operadores de máquinas para fabricar accesorios fotográficos" },
        { "codigo": "8276", "descripcion": "Operadores de máquinas para fabricar azúcares" },
        { "codigo": "8212", "descripcion": "Operadores de máquinas para fabricar cemento y otros productos minerales" },
        { "codigo": "8222", "descripcion": "Operadores de máquinas para fabricar municiones y explosivos" },
        { "codigo": "8231", "descripcion": "Operadores de máquinas para fabricar productos de caucho" },
        { "codigo": "8240", "descripcion": "Operadores de máquinas para fabricar productos de madera" },
        { "codigo": "8232", "descripcion": "Operadores de máquinas para fabricar productos de material plástico" },
        { "codigo": "8253", "descripcion": "Operadores de máquinas para fabricar productos de papel" },
        { "codigo": "8221", "descripcion": "Operadores de máquinas para fabricar productos farmacéuticos y cosméticos" },
        { "codigo": "8229", "descripcion": "Operadores de máquinas para fabricar productos químicos, no clasificados bajo otros epígrafes" },
        { "codigo": "8269", "descripcion": "Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero, no clasificados bajo otros epígrafes" },
        { "codigo": "8266", "descripcion": "Operadores de máquinas para la fabricación de calzado y afines" },
        { "codigo": "8273", "descripcion": "Operadores de máquinas para moler cereales y especias" },
        { "codigo": "8223", "descripcion": "Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales" },
        { "codigo": "8124", "descripcion": "Operadores de máquinas trefiladoras y estiradoras de metales" },
        { "codigo": "8172", "descripcion": "Operadores de robots industriales" },
        { "codigo": "8262", "descripcion": "Operadores de telares y otras máquinas tejedoras" },
        { "codigo": "7414", "descripcion": "Operarios de la conservación de frutas. legumbres, verduras y afines" },
        { "codigo": "7413", "descripcion": "Operarios de la elaboración de productos lácteos" },
        { "codigo": "7344", "descripcion": "Operarios de la fotografía y afines" },
        { "codigo": "7421", "descripcion": "Operarios del tratamiento de la madera" },
        { "codigo": "7123", "descripcion": "Operarios en cemento armado, enfoscadores y afines" },
        { "codigo": "1239", "descripcion": "Otros directores de departamentos, no clasificados bajo otros epígrafes" },
        { "codigo": "3340", "descripcion": "Otros maestros e instructores de nivel medio" },
        { "codigo": "4190", "descripcion": "Otros oficinistas" },
        { "codigo": "8290", "descripcion": "Otros operadores de máquinas y montadores" },
        { "codigo": "2359", "descripcion": "Otros profesionales de la enseñanza, no clasificados bajo otros epígrafes" },
        { "codigo": "5149", "descripcion": "Otros trabajadores de servicios personales a particulares. no clasificados bajo otros epígrafes" },
        { "codigo": "4212", "descripcion": "Pagadores y cobradores de ventanilla y taquilleros" },
        { "codigo": "7412", "descripcion": "Panaderos, pasteleros y confiteros" },
        { "codigo": "7132", "descripcion": "Parqueteros y colocadores de suelos" },
        { "codigo": "7435", "descripcion": "Patronistas y cortadores de tela, cuero y afine" },
        { "codigo": "3474", "descripcion": "Payasos, prestidigitadores, acróbatas y afines" },
        { "codigo": "7112", "descripcion": "Pegadores" },
        { "codigo": "7434", "descripcion": "Peleteros y afines" },
        { "codigo": "5141", "descripcion": "Peluqueros, especialistas en tratamientos de belleza y afines" },
        { "codigo": "9333", "descripcion": "Peones de carga" },
        { "codigo": "9313", "descripcion": "Peones de la construcción de edificios" },
        { "codigo": "9213", "descripcion": "Peones de la pesca, la caza y la trampa" },
        { "codigo": "9311", "descripcion": "Peones de minas y canteras" },
        { "codigo": "9321", "descripcion": "Peones de montaje" },
        { "codigo": "9312", "descripcion": "Peones de obras públicas y mantenimiento: carreteras, presas y obras similares" },
        { "codigo": "9212", "descripcion": "Peones forestales" },
        { "codigo": "8113", "descripcion": "Perforadores y sondistas de pozos y afines" },
        { "codigo": "3231", "descripcion": "Personal de enfermería de nivel medio" },
        { "codigo": "2230", "descripcion": "Personal de enfermería y partería de nivel superior" },
        { "codigo": "5169", "descripcion": "Personal de los servicios de protección y seguridad, no clasificado bajo otros epígrafes" },
        { "codigo": "3232", "descripcion": "Personal de partería de nivel medio" },
        { "codigo": "5143", "descripcion": "Personal de pompas fúnebres y embalsamadores" },
        { "codigo": "1120", "descripcion": "Personal directivo de la administración pública" },
        { "codigo": "9131", "descripcion": "Personal doméstico" },
        { "codigo": "6152", "descripcion": "Pescadores de agua dulce y en aguas costeras" },
        { "codigo": "6153", "descripcion": "Pescadores de alta mar" },
        { "codigo": "3143", "descripcion": "Pilotos de aviación y afines" },
        { "codigo": "7324", "descripcion": "Pintores decoradores de vidrio, cerámica y otros materiales" },
        { "codigo": "7141", "descripcion": "Pintores y empapeladores" },
        { "codigo": "5162", "descripcion": "Policías" },
        { "codigo": "9152", "descripcion": "Porteros y guardianes y afines" },
        { "codigo": "3241", "descripcion": "Practicantes de la medicina tradicional" },
        { "codigo": "3221", "descripcion": "Practicantes y asistentes médicos" },
        { "codigo": "7431", "descripcion": "Preparadores de fibras" },
        { "codigo": "7416", "descripcion": "Preparadores y elaboradores de tabaco y sus productos" },
        { "codigo": "4214", "descripcion": "Prestamistas" },
        { "codigo": "6130", "descripcion": "Productores y trabajadores agropecuarios calificados cuya producción se destina al mercado" },
        { "codigo": "2139", "descripcion": "Profesionales de la informática, no clasificados bajo otros epígrafes" },
        { "codigo": "3431", "descripcion": "Profesionales de nivel medio de servicios administrativos y afines" },
        { "codigo": "3439", "descripcion": "Profesionales de nivel medio de servicios de administración, no clasificados bajo otros epígrafes" },
        { "codigo": "3434", "descripcion": "Profesionales de nivel medio de servicios estadísticos, matemáticos y afines" },
        { "codigo": "3432", "descripcion": "Profesionales de nivel medio del derecho y servicios legales o afines" },
        { "codigo": "3419", "descripcion": "Profesionales de nivel medio en operaciones financieras y comerciales, no clasificados bajo otros epígrafes" },
        { "codigo": "2429", "descripcion": "Profesionales del derecho, no clasificados bajo otros epígrafes" },
        { "codigo": "2446", "descripcion": "Profesionales del trabajo social" },
        { "codigo": "3229", "descripcion": "Profesionales nivel medio medicina moderna/salud (excepto personal enfermería y partería) no clasificados bajo otro epígrafes" },
        { "codigo": "2320", "descripcion": "Profesores de la enseñanza secundaria" },
        { "codigo": "2310", "descripcion": "Profesores de universidades y otros establecimientos de la enseñanza superior" },
        { "codigo": "2132", "descripcion": "Programadores informáticos" },
        { "codigo": "2445", "descripcion": "Psicólogos" },
        { "codigo": "7224", "descripcion": "Pulidores de metales y afiladores de herramientas" },
        { "codigo": "2113", "descripcion": "Químicos" },
        { "codigo": "4222", "descripcion": "Recepcionistas y empleados de informaciones" },
        { "codigo": "4213", "descripcion": "Receptores de apuestas y afines" },
        { "codigo": "9161", "descripcion": "Recolectores de basura" },
        { "codigo": "9153", "descripcion": "Recolectores de dinero en aparatos de venta automática, lectores de medidores y afines" },
        { "codigo": "7423", "descripcion": "Reguladores y reguladores-operadores de máquinas de labrar madera" },
        { "codigo": "7223", "descripcion": "Reguladores y reguladores-operadores de máquinas herramientas" },
        { "codigo": "3415", "descripcion": "Representantes comerciales y técnicos de ventas" },
        { "codigo": "5112", "descripcion": "Revisores, guardas y cobradores de los transportes públicos" },
        { "codigo": "7133", "descripcion": "Revocadores" },
        { "codigo": "2460", "descripcion": "Sacerdotes de distintas religiones" },
        { "codigo": "7433", "descripcion": "Sastres, modistos y sombrereros" },
        { "codigo": "4115", "descripcion": "Secretarios" },
        { "codigo": "9999", "descripcion": "Seleccione puesto" },
        { "codigo": "2442", "descripcion": "Sociólogos, antropólogos y afines" },
        { "codigo": "7212", "descripcion": "Soldadores y oxicortadores" },
        { "codigo": "7322", "descripcion": "Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio" },
        { "codigo": "6141", "descripcion": "Taladores y otros trabajadores forestales" },
        { "codigo": "7437", "descripcion": "Tapiceros, colchoneros y afines" },
        { "codigo": "4111", "descripcion": "Taquígrafos y mecanógrafos" },
        { "codigo": "3417", "descripcion": "Tasadores y subastadores" },
        { "codigo": "7131", "descripcion": "Techadores" },
        { "codigo": "7432", "descripcion": "Tejedores con telares o de tejidos de punto afines" },
        { "codigo": "4223", "descripcion": "Telefonistas" },
        { "codigo": "3433", "descripcion": "Tenedores de libros" },
        { "codigo": "6210", "descripcion": "Trabajadores agropecuarios y pesqueros de subsistencia" },
        { "codigo": "5139", "descripcion": "Trabajadores de los cuidados personales y afines, no clasificados bajo otros epígrafes" },
        { "codigo": "3460", "descripcion": "Trabajadores y asistentes sociales de nivel medio" },
        { "codigo": "7113", "descripcion": "Tronzadores, labrantes y grabadores de piedra" },
        { "codigo": "3212", "descripcion": "Técnicos en agronomía, zootecnia y silvicultura" },
        { "codigo": "3211", "descripcion": "Técnicos en ciencias biológicas y afines" },
        { "codigo": "3111", "descripcion": "Técnicos en ciencias físicas y químicas" },
        { "codigo": "3119", "descripcion": "Técnicos en ciencias físicas y químicas y en ingeniería, no clasificados bajo otros epígrafes" },
        { "codigo": "3122", "descripcion": "Técnicos en control de equipos informáticos" },
        { "codigo": "3123", "descripcion": "Técnicos en control de robots industriales" },
        { "codigo": "3223", "descripcion": "Técnicos en dietética y nutrición" },
        { "codigo": "3114", "descripcion": "Técnicos en electrónica y telecomunicaciones" },
        { "codigo": "3112", "descripcion": "Técnicos en ingeniería civil" },
        { "codigo": "3117", "descripcion": "Técnicos en ingeniería de minas y metalurgia" },
        { "codigo": "3115", "descripcion": "Técnicos en mecánica y construcción mecánica" },
        { "codigo": "3224", "descripcion": "Técnicos en optometría y ópticos" },
        { "codigo": "3121", "descripcion": "Técnicos en programación informática" },
        { "codigo": "3116", "descripcion": "Técnicos en química industrial" },
        { "codigo": "3145", "descripcion": "Técnicos en seguridad aeronáutica" },
        { "codigo": "3228", "descripcion": "Técnicos y asistentes farmacéuticos" },
        { "codigo": "3227", "descripcion": "Técnicos y asistentes veterinarios" },
        { "codigo": "9113", "descripcion": "Vendedores a domicilio y por teléfono" },
        { "codigo": "9111", "descripcion": "Vendedores ambulantes de productos comestibles" },
        { "codigo": "9112", "descripcion": "Vendedores ambulantes de productos no comestibles" },
        { "codigo": "5230", "descripcion": "Vendedores de quioscos y de puestos de mercado" },
        { "codigo": "5220", "descripcion": "Vendedores y demostradores de tiendas y almacenes" },
        { "codigo": "2223", "descripcion": "Veterinarios" },
        { "codigo": "7442", "descripcion": "Zapateros y afines" }
    ]
}
var EGTS = {
    "datos": [
        { "codigo": "1", "descripcion": "CONTINUOS" },
        { "codigo": "2", "descripcion": "DISCONTINUOS" }
    ]
}

var ETS = {
    "datos": [
        { "codigo": "000", "descripcion": "SERVICIOS COMUNES CONTINUOS" }
    ]
}
var ESR = {
    "datos": [
        { "codigo": "25", "descripcion": "Abandono del trabajo/ Art.244 LCT" },
        { "codigo": "1", "descripcion": "Activo" },
        { "codigo": "51", "descripcion": "Baja de oficio por denuncia" },
        { "codigo": "7", "descripcion": "Baja por despido" },
        { "codigo": "0", "descripcion": "Baja por fallecimiento" },
        { "codigo": "2", "descripcion": "Bajas otras causales" },
        { "codigo": "40", "descripcion": "Cesantía laboral" },
        { "codigo": "20", "descripcion": "Cesión del personal / ART.229 - LCT" },
        { "codigo": "32", "descripcion": "Concurso del Empleador Art.251 LCT" },
        { "codigo": "44", "descripcion": "Conservación del empleo P/accidente o enfermedad inculpable" },
        { "codigo": "23", "descripcion": "Denuncia de contrato de trabajo por el empleador/ Art.242 LCT" },
        { "codigo": "24", "descripcion": "Denuncia de contrato de trabajo por el trabajador/ Art.242 LCT" },
        { "codigo": "19", "descripcion": "Denuncia del contrato de trabajo por transferencia de establecimiento -ART.226 - LCT" },
        { "codigo": "26", "descripcion": "Despido / ART. 245 - LCT" },
        { "codigo": "39", "descripcion": "Despido Art.5° Ley 25371" },
        { "codigo": "36", "descripcion": "Despido con o sin justa causa / ART.64 Inc.c) Ley 22248" },
        { "codigo": "37", "descripcion": "Despido por fuerza mayor-Trabajo Agrario/Art.64 Inc.d) L.22248" },
        { "codigo": "15", "descripcion": "E.S.E.Cese transitorio de servicios" },
        { "codigo": "42", "descripcion": "Empleado eventual en EU (para uso de la ESE) mes completo" },
        { "codigo": "43", "descripcion": "Empleado eventual en EU (para uso de la ESE) mes incompleto" },
        { "codigo": "41", "descripcion": "Exoneración" },
        { "codigo": "29", "descripcion": "Fallecimiento del empleador/ Art.249 LCT" },
        { "codigo": "27", "descripcion": "Falta o disminución del trabajo/ Art.247 LCT" },
        { "codigo": "47", "descripcion": "Fin Pago Retiro Voluntario - Dec.263/2018 y otros" },
        { "codigo": "38", "descripcion": "Fin contrato de aprendizaje y pasantias / ART.1 y 2 Ley 25877; ART.2 y 19 Ley 25013" },
        { "codigo": "28", "descripcion": "Fuerza mayor / ART.247 - LCT" },
        { "codigo": "34", "descripcion": "Incapacidad o inhabilidad del trabajador / ART.254 - LCT" },
        { "codigo": "46", "descripcion": "Inicio Pago Retiro Voluntario - Dec.263/2018 y otros" },
        { "codigo": "33", "descripcion": "Jubilación/ Art.252 LCT / Art.64 Inc.e) L.22248 y otras" },
        { "codigo": "10", "descripcion": "Licencia por excedencia" },
        { "codigo": "5", "descripcion": "Licencia por maternidad" },
        { "codigo": "11", "descripcion": "Licencia por maternidad Down" },
        { "codigo": "12", "descripcion": "Licencia por vacaciones" },
        { "codigo": "13", "descripcion": "Licencia sin goce de haberes" },
        { "codigo": "16", "descripcion": "Personal siniestrado de terceros" },
        { "codigo": "31", "descripcion": "Quiebra del empleador/Art.251 LCT" },
        { "codigo": "17", "descripcion": "Reingreso por disposición judicial" },
        { "codigo": "21", "descripcion": "Renuncia del trabajador / ART.240 - LCT / ART.64 Inc.a) L22248 y otras" },
        { "codigo": "14", "descripcion": "Reserva de puesto" },
        { "codigo": "49", "descripcion": "Susp. período parcial L 20744 art.223bis / Res. 397 MTEySS" },
        { "codigo": "48", "descripcion": "Suspendido. Res. 397/2020 MTEySS c/Aportes OS" },
        { "codigo": "9", "descripcion": "Suspendido.Ley 20744 Art. 223 Bis" },
        { "codigo": "6", "descripcion": "Suspensiones otras causales" },
        { "codigo": "45", "descripcion": "Suspensiones por causas disciplinarias" },
        { "codigo": "18", "descripcion": "Transferencia del contrato de trabajo ART.225 LCT" },
        { "codigo": "99", "descripcion": "Vencimiento de contrato a plazo fijo o determinado, a tiempo completo o parcial" },
        { "codigo": "30", "descripcion": "Vencimiento de plazo / ART. 250 - LCT" },
        { "codigo": "22", "descripcion": "Voluntad concurrente de las partes - ART.241 - LCT acuerdo homologado o no homologado" },
        { "codigo": "35", "descripcion": "Voluntad concurrente de las partes-Trabajo Agrario/Art.64 Inc.b) L.22248" }
    ]
}

var EMC = {
    "datos": [
        { "codigo": "000", "descripcion": "Contrato Modalidad Promovida. Reducción 0%" },
        { "codigo": "001", "descripcion": "A tiempo parcial: Indeterminado/permanente" },
        { "codigo": "002", "descripcion": "Becarios - Residencias médicas Ley N° 22.127" },
        { "codigo": "003", "descripcion": "De aprendizaje Ley N° 25.013" },
        { "codigo": "004", "descripcion": "Especial de Fomento del Empleo Ley N° 24.465" },
        { "codigo": "005", "descripcion": "Fomento del Empleo Ley N° 24.013 y Ley N° 24.465" },
        { "codigo": "006", "descripcion": "Lanzamiento nueva actividad. Idem 005" },
        { "codigo": "007", "descripcion": "Período de prueba Ley N° 24.465 y Ley N° 25.013" },
        { "codigo": "008", "descripcion": "A Tiempo completo indeterminado/Trabajo permanente" },
        { "codigo": "009", "descripcion": "Práctica laboral para jóvenes" },
        { "codigo": "010", "descripcion": "Pasantías Ley N° 25.165 Decreto N° 340/92" },
        { "codigo": "010", "descripcion": "Pasantías - sin obra social" },
        { "codigo": "011", "descripcion": "Trabajo de temporada" },
        { "codigo": "012", "descripcion": "Trabajo eventual" },
        { "codigo": "013", "descripcion": "Trabajo formación" },
        { "codigo": "014", "descripcion": "Nuevo Período de Prueba" },
        { "codigo": "015", "descripcion": "Puesto Nuevo Varones y Mujeres de 25 a 44 años Ley N° 25.250" },
        { "codigo": "016", "descripcion": "Nuevo Período de Prueba Trabajador Discapacitado Art. 34 Ley N° 24.147" },
        { "codigo": "017", "descripcion": "Puesto Nuevo menor de 25 años, Varones y Mujeres de 45 o más años y Mujer Jefe de familia S/límite/edad Ley 25250" },
        { "codigo": "018", "descripcion": "Trabajador Discapacitado Art. 34 Ley N° 24.147" },
        { "codigo": "019", "descripcion": "Puesto Nuevo Varones y Mujeres 25 a 44 años Art. 34 Ley N° 24.147 Ley N° 25.250" },
        { "codigo": "020", "descripcion": "Puesto Nuevo Menor 25 años, Varones y Mujeres 45 o más y Mujer Jefe de familia S/límite de edad. Art. 34 Ley N° 24.147 y Ley N° 25.250" },
        { "codigo": "021", "descripcion": "A tiempo parcial determinado (contrato a plazo fijo)" },
        { "codigo": "022", "descripcion": "A Tiempo completo determinado (contrato a plazo fijo)" },
        { "codigo": "023", "descripcion": "Personal no permanente Ley N° 22.248" },
        { "codigo": "024", "descripcion": "Personal de la Construcción Ley N° 22.250" },
        { "codigo": "025", "descripcion": "Empleo público provincial" },
        { "codigo": "026", "descripcion": "Beneficiario de programa de empleo, capacitación y de recuperación productiva" },
        { "codigo": "027", "descripcion": "Pasantías Decreto N° 1.227/01" },
        { "codigo": "027", "descripcion": "Pasantías Ley N° 26.427 -con obra social28 Programas Jefes y Jefas de Hogar" },
        { "codigo": "029", "descripcion": "Decreto N° 1.212/03 Aportante Autónomo" },
        { "codigo": "030", "descripcion": "Nuevo Periodo de Prueba Trabajador Discapacitado Art. 87 Ley N° 24.013" },
        { "codigo": "031", "descripcion": "Trabajador Discapacitado Art. 87 Ley N° 24.013" },
        { "codigo": "032", "descripcion": "Periodo de Prueba Art. 6° Ley N° 25.877." },
        { "codigo": "033", "descripcion": "Periodo de Prueba Art. 6° Ley N° 25.877 Beneficiarios de planes Jefes y Jefas de hogar" },
        { "codigo": "034", "descripcion": "Periodo de Prueba Art. 6° Ley N° 25.877. Art. 34 Ley N° 24.147" },
        { "codigo": "035", "descripcion": "Periodo de Prueba Art. 6° Ley N° 25.877. Art. 34. Ley N° 24.147 Beneficiarios de planes Jefes y Jefas de hogar" },
        { "codigo": "036", "descripcion": "Periodo de Prueba Art. 6° Ley N° 25.877.Trabajador Discapacitado Art. 87 Ley N° 24.013" },
        { "codigo": "037", "descripcion": "Periodo de Prueba Art. 6° Ley N° 25.877. Trabajador Discapacitado Art. 87 Ley N° 24.013 Beneficiarios planes Jefes y Jefas hogar" },
        { "codigo": "038", "descripcion": "Puesto Nuevo Art. 6° Ley N° 25.877." },
        { "codigo": "039", "descripcion": "Puesto Nuevo Art. 6° Ley N° 25.877. Beneficiarios de planes Jefes y Jefas de hogar" },
        { "codigo": "040", "descripcion": "Puesto Nuevo Art. 6° Ley N° 25.877. Art. 34 Ley N° 24.147 " },
        { "codigo": "041", "descripcion": "Puesto Nuevo Art. 6° Ley N° 25.877. Art. 34 Ley N° 24.147. Beneficiarios de planes Jefes y Jefas de hogar" },
        { "codigo": "042", "descripcion": "Puesto Nuevo Art. 6° Ley N° 25.877.Trabajador Discapacitado Art. 87 Ley N° 24.013" },
        { "codigo": "043", "descripcion": "Puesto Nuevo Art. 6° Ley N° 25.877. Trabajador Discapacitado Art 87 Ley N° 24.013 Beneficiario planes Jefes y Jefas hogar" },
        { "codigo": "044", "descripcion": "Changa Solidaria. CCT 62/75" },
        { "codigo": "045", "descripcion": "Personal no permanente hoteles CCT 362/03 Art. 68 inc. B" },
        { "codigo": "046", "descripcion": "Planta transitoria Administración Pública Nacional, Provincial y/o Municipal" },
        { "codigo": "047", "descripcion": "Representación gremial" },
        { "codigo": "048", "descripcion": "Art.4° Ley N° 24.241Traslado temporario desde el exterior ó Conv bilaterales de Seguridad Social" },
        { "codigo": "049", "descripcion": "Directores - empleado SA con Obra Social y LRT" },
        { "codigo": "050", "descripcion": "Contrato Modalidad Promovida. Reducción 50%" },
        { "codigo": "051", "descripcion": "Pasantías Ley N° 26.427 -con obra social- beneficiario pensión de discapacidad" },
        { "codigo": "095", "descripcion": "Planes Ministerio de Trabajo" },
        { "codigo": "096", "descripcion": "Plan Trabajo por San Luis Ley N° 5.411/03" },
        { "codigo": "097", "descripcion": "Programa Trabajo para jóvenes tucumanos" },
        { "codigo": "098", "descripcion": "BONUS 2da Oportunidad" },
        { "codigo": "099", "descripcion": "LRT (Directores SA, municipios, org, cent y descent. Emp mixt docentes privados o publicos de jurisdicciones incorporadas o no al SIJP)" },
        { "codigo": "100", "descripcion": "Contrato Modalidad Promovida. Reducción 100%" },
        { "codigo": "102", "descripcion": "Personal Permanente Discontinuo con ART (para uso de la E.U.)" },
        { "codigo": "110", "descripcion": "Trabajo permanente prestación continua Ley N° 26.727" },
        { "codigo": "111", "descripcion": "Trabajo temporario Ley N° 26.727" },
        { "codigo": "112", "descripcion": "Trabajo permanente discontinuo Ley N° 26.727" },
        { "codigo": "113", "descripcion": "Trabajo por equipo o cuadrilla familiar Ley N° 26.727" },
        { "codigo": "114", "descripcion": "Trabajo temporario con Reducción Ley N° 26.727" },
        { "codigo": "115", "descripcion": "Trabajo permanente discontinuo con Reducción Ley N° 26.727" },
        { "codigo": "201", "descripcion": "Puesto nuevo Art. 16 Ley N° 26.476 - beneficio primeros doce meses" },
        { "codigo": "202", "descripcion": "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 34 Ley N° 24.147 - beneficio primeros doce meses" },
        { "codigo": "203", "descripcion": "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 87 Ley N° 24.013 - beneficio primeros doce meses" },
        { "codigo": "204", "descripcion": "Puesto nuevo Art. 16 Ley N° 26.476 meses 13 a 24 - beneficio segundo año " },
        { "codigo": "205", "descripcion": "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 34 Ley N° 24.147 meses 13 a 24 - beneficio segundo año" },
        { "codigo": "206", "descripcion": "Puesto nuevo Art. 16 Ley N° 26.476 Trabajador discapacitado Art. 87 Ley N° 24.013 meses 13 a 24 - beneficio segundo año" },
        { "codigo": "211", "descripcion": "Art. 11 inc. b Ley N° 26.476 Regularización personal no registrado" },
        { "codigo": "212", "descripcion": "Art. 11 inc. b Ley N° 26.476. Regularización personal no registrado Trabajador discapacitado Art. 34 Ley N° 24.147" },
        { "codigo": "213", "descripcion": "Art. 11 inc. b Ley N° 26.476. Regularización personal no registrado Trabajador discapacitado Art. 87 Ley N° 24.013" },
        { "codigo": "221", "descripcion": "Art. 12 Ley N° 26.476 Regularización personal no registrado" },
        { "codigo": "222", "descripcion": "Art. 12 Ley N° 26.476 Regularización personal no registrado Trabajador discapacitado Art. 34 Ley N° 24.147" },
        { "codigo": "223", "descripcion": "Art. 12 Ley N° 26.476 Regularización personal no registrado trabajador discapacitado Art. 87 Ley N° 24.013" },
        { "codigo": "301", "descripcion": "Art. 19 Ley 26940. Tiempo indeterminado" },
        { "codigo": "302", "descripcion": "Art. 19 Ley 26940. Trabajador discapacitado art. 34 L 24147. Tiempo indeterminado" },
        { "codigo": "303", "descripcion": "Art. 19 Ley 26940. Trabajador discapacitado art. 87 L 24013. Tiempo indeterminado" },
        { "codigo": "304", "descripcion": "Art. 19 Ley 26940. Tiempo parcial. Art. 92 ter LCT" },
        { "codigo": "305", "descripcion": "Art. 19 Ley 26940. Trabajador discapacitado art. 34 L 24147. Tiempo parcial. Art. 92 ter LCT" },
        { "codigo": "306", "descripcion": "Art. 19 Ley 26940. Trabajador discapacitado art. 87 L 24013. Tiempo parcial. Art. 92 ter LCT" },
        { "codigo": "307", "descripcion": "Art. 24 Ley 26940. Hasta 15 empleados. Primeros 12 meses. Tiempo indeterminado " },
        { "codigo": "308", "descripcion": "Art. 24 Ley 26940. Hasta 15 empleados. Primeros 12 meses. Tiempo indeterminado/Trabajador discapacitado art. 34 Ley 24147" },
        { "codigo": "309", "descripcion": "Art. 24 Ley 26940. Hasta 15 empleados. Primeros 12 meses. Tiempo indeterminado/Trabajador discapacitado art. 87 Ley 24013" },
        { "codigo": "310", "descripcion": "Art. 24 Ley 26940. Hasta 15 empleados. Segundos 12 meses. Tiempo indeterminado" },
        { "codigo": "311", "descripcion": "Art. 24 Ley 26940. Hasta 15 empleados. Segundos 12 meses. Tiempo indeterminado. Trabajador discapacitado art. 34 Ley 24147" },
        { "codigo": "312", "descripcion": "Art. 24 Ley 26940. Hasta 15 empleados. Segundos 12 meses. Tiempo indeterminado. Trabajador discapacitado art. 87 Ley 24013" },
        { "codigo": "313", "descripcion": "Art. 24 Ley 26940. 16 a 80 empleados. Tiempo indeterminado" },
        { "codigo": "314", "descripcion": "Art. 24 Ley 26940. 16 a 80 empleados. Tiempo indeterminado. Trabajador discapacitado art. 34 Ley 24147" },
        { "codigo": "315", "descripcion": "Art. 24 Ley 26940. 16 a 80 empleados. Tiempo indeterminado. Trabajador discapacitado art. 87 Ley 24013" },
        { "codigo": "985", "descripcion": "CCG Vitivinícola de Neuquén" },
        { "codigo": "987", "descripcion": "CCG Vitivinícola de La Rioja" },
        { "codigo": "989", "descripcion": "CCG Tabaco Salta" },
        { "codigo": "990", "descripcion": "CCG Tabaco Jujuy" },
        { "codigo": "991", "descripcion": "CCG Vitivinícola de Río Negro" },
        { "codigo": "992", "descripcion": "CCG Multiproducto del Chaco" },
        { "codigo": "994", "descripcion": "CCG Yerba Mate Misiones y Corrientes" },
        { "codigo": "995", "descripcion": "CCG Vitivinícola de San Juan" },
        { "codigo": "996", "descripcion": "CCG Vitivinícola de Mendoza" },
        { "codigo": "997", "descripcion": "CCG forestal del Chaco" },
        { "codigo": "998", "descripcion": "CCG tabaco Virginia del Chaco" },
        { "codigo": "999", "descripcion": "Art. 11 Ley N° 26.476.Trabajador registrado. Rectificación real fecha de inicio" }
    ]
}

var modalidadLiquicion = {
    "datos": [
        { "codigo": "1", "descripcion": "MES" },
        { "codigo": "2", "descripcion": "QUINCENA" },
        { "codigo": "3", "descripcion": "SEMANA" },
        { "codigo": "4", "descripcion": "DIA" },
        { "codigo": "5", "descripcion": "HORA" },
        { "codigo": "6", "descripcion": "PIEZA" },
        { "codigo": "7", "descripcion": "A COMISION" },
        { "codigo": "8", "descripcion": "JORNAL" }
    ]
}

var TS = {
    "datos": [
        { "codigo": "J", "descripcion": "JORNAL" },
        { "codigo": "M", "descripcion": "MENSUAL" },
        { "codigo": "D", "descripcion": "DIARIO" }
    ]
}
